(async () => {
  'use strict';
  const D=window.InvitationData,$=selector=>document.querySelector(selector);
  let draft=await D.loadAsync(),dirty=false,active='celebracion',previewReady=false,previewTimer,toastTimer;
  const sections=[
    ['celebracion','La celebración','La protagonista.','LOS DATOS DE TU CELEBRACIÓN','Empieza por los nombres y las fechas. Puedes personalizar todos los textos e imágenes en las siguientes secciones.','#inicio'],
    ['textos','Textos y narrativa','Tu propia historia.','CADA PALABRA CUENTA','Edita la carta, la historia y todos los títulos. Los saltos de línea se conservan en los grandes titulares.','#gaceta'],
    ['imagenes','Fotografías','Tu álbum, tu estilo.','EL ARTE DE LOS RECUERDOS','Personaliza las cinco fotos del carrusel de portada. Sube imágenes, ajusta el encuadre y edita las demás fotografías.','#inicio'],
    ['itinerario','El itinerario','El orden del baile.','CADA MOMENTO DE LA NOCHE','Añade, cambia de orden o elimina momentos. La hora se muestra tal como la escribas.','#velada'],
    ['lugar','El lugar','El escenario.','DONDE SUCEDE LA MAGIA','Cambia el lugar y sus enlaces. La imagen actual es de ambientación; puedes subir una fotografía real del salón.','#lugar'],
    ['detalles','Vestimenta y regalos','Los pequeños detalles.','TODO LO QUE TUS INVITADOS NECESITAN','Personaliza la vestimenta y los regalos. Los datos bancarios y las tiendas solo aparecen cuando los completas.','#detalles'],
    ['rsvp','WhatsApp y RSVP','Una respuesta para ti.','RECIBE LAS CONFIRMACIONES','Aquí eliges el WhatsApp que recibirá las respuestas. El invitado prepara su mensaje y lo envía desde WhatsApp.','#confirmar'],
    ['musica','La música','La banda sonora.','UN BAILE PARA RECORDAR','La música comienza cuando el invitado pulsa Escuchar. Puedes subir tu audio o elegir un video de YouTube.','#inicio'],
    ['avanzado','Opciones y respaldo','Todo en su lugar.','GUARDA Y COMPARTE','Los cambios se guardan en este navegador. Descarga la invitación para compartirla y un respaldo para seguir editando.','#confirmar']
  ];
  const get=path=>path.split('.').reduce((value,key)=>value?.[key],draft);
  function set(path,value){const keys=path.split('.');let obj=draft;for(const key of keys.slice(0,-1))obj=obj[key];obj[keys.at(-1)]=value;changed();}
  function el(tag,className,text){const out=document.createElement(tag);if(className)out.className=className;if(text!==undefined)out.textContent=text;return out;}
  function toast(text){$('#editorToast').textContent=text;$('#editorToast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#editorToast').classList.remove('visible'),5000);}
  function changed(){dirty=true;$('#saveStatus').textContent='Cambios sin guardar';$('#editorErrors').hidden=true;updatePhone();clearTimeout(previewTimer);previewTimer=setTimeout(sendPreview,240);}
  function updatePhone(){const value=draft.rsvp.whatsapp.replace(/[\s()+-]/g,'');const valid=/^[1-9]\d{7,14}$/.test(value);$('#phoneStatus').textContent=valid?'WhatsApp configurado: +'+value:'WhatsApp pendiente';$('#phoneStatus').classList.toggle('ready',valid);$('.editor-brand-mark').textContent=draft.iniciales;}
  function sendPreview(){if(previewReady)$('#previewFrame').contentWindow.postMessage({type:'invitation:preview',config:draft},location.protocol==='file:'?'*':location.origin);}
  function showErrors(errors){const box=$('#editorErrors');box.hidden=!errors.length;box.textContent=errors.join('\n');if(errors.length){$('.editor-controls').scrollTop=0;box.scrollIntoView({block:'nearest',behavior:'smooth'});}}
  function field(path,label,type='text',hint='',options={}) {
    const wrap=el('div','edit-field'+(type==='checkbox'?' check-field':''));const id='edit-'+path.replace(/\./g,'-');const title=el('label','',label);title.htmlFor=id;
    const input=el(type==='textarea'?'textarea':type==='select'?'select':'input');input.id=id;input.dataset.path=path;
    if(type==='select')options.items.forEach(([value,name])=>{const item=el('option','',name);item.value=value;input.append(item);});else if(type!=='textarea')input.type=type;
    if(type==='checkbox')input.checked=!!get(path);else input.value=get(path) ?? '';
    if(type==='number'||type==='range'){input.min=String(options.min??0);input.max=String(options.max??100);input.step=String(options.step??1);}
    if(type==='textarea'){input.rows=options.rows || 3;input.maxLength=10000;}else if(['text','tel','url'].includes(type))input.maxLength=type==='url'?4000:2000;
    input.addEventListener(type==='checkbox'||type==='select'?'change':'input',()=>{set(path,type==='checkbox'?input.checked:['number','range'].includes(type)?Number(input.value):input.value);options.onChange?.();});
    if(type==='checkbox'){title.prepend(input);wrap.append(title);}else wrap.append(title,input);if(hint)wrap.append(el('small','',hint));return wrap;
  }
  function group(title){$('#editorFields').append(el('h2','edit-group-heading',title));}
  function notice(text){$('#editorFields').append(el('p','field-notice',text));}
  function row(...fields){const wrap=el('div','edit-row');wrap.append(...fields);return wrap;}
  function wallTime(iso,zone=draft.zonaHoraria){try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}T${v.hour}:${v.minute}`;}catch{return '';}}
  function zonedISO(wall,zone){
    if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(wall))return '';
    const base=Date.parse(wall+':00Z');let candidate=base;
    for(let i=0;i<3;i++){const formatted=wallTime(new Date(candidate).toISOString(),zone);const diff=base-Date.parse(formatted+':00Z');if(!diff)break;candidate+=diff;}
    if(wallTime(new Date(candidate).toISOString(),zone)!==wall)throw new Error('Esa hora no existe en la zona horaria elegida.');
    const offset=Math.round((base-candidate)/60000);return wall+':00'+(offset>=0?'+':'-')+String(Math.floor(Math.abs(offset)/60)).padStart(2,'0')+':'+String(Math.abs(offset)%60).padStart(2,'0');
  }
  function dateField(path,label){const wrap=el('div','edit-field'),input=el('input');input.type='datetime-local';input.id='edit-'+path;input.value=wallTime(get(path));const title=el('label','',label);title.htmlFor=input.id;input.addEventListener('change',()=>{try{set(path,zonedISO(input.value,draft.zonaHoraria));updateDateText();}catch(error){toast(error.message);}});wrap.append(title,input);return wrap;}
  function updateDateText(){try{const f=new Intl.DateTimeFormat('es-PA',{timeZone:draft.zonaHoraria,weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(draft.fechaISO));draft.fechaTexto=f.charAt(0).toUpperCase()+f.slice(1);const format=iso=>new Intl.DateTimeFormat('en-US',{timeZone:draft.zonaHoraria,hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(iso));draft.horaTexto=format(draft.fechaISO)+' — '+format(draft.fechaFinISO);for(const path of ['fechaTexto','horaTexto']){const input=document.getElementById('edit-'+path);if(input)input.value=draft[path];}changed();}catch{/* validated on save */}}
  function renderCelebration(){const target=$('#editorFields');target.append(field('nombreCompleto','Nombre completo'),row(field('nombre','Nombre corto'),field('iniciales','Iniciales del monograma')),field('edad','Edad','text','Se usa en los elementos gráficos del gran debut.'));group('La fecha y la hora');
    const zone=field('zonaHoraria','Zona horaria','select','El contador y el calendario usan esta zona.',{items:[['America/Panama','Panamá · UTC −05:00'],['America/Bogota','Colombia · UTC −05:00'],['America/Lima','Perú · UTC −05:00'],['America/Mexico_City','Ciudad de México'],['America/New_York','Nueva York'],['America/Santo_Domingo','República Dominicana'],['America/Argentina/Buenos_Aires','Buenos Aires'],['Europe/Madrid','Madrid']],onChange:()=>{try{for(const path of ['fechaISO','fechaFinISO'])draft[path]=zonedISO($('#edit-'+path).value,draft.zonaHoraria);updateDateText();}catch(error){toast(error.message);}}});
    const select=zone.querySelector('select');if(![...select.options].some(opt=>opt.value===draft.zonaHoraria)){const option=el('option','',draft.zonaHoraria);option.value=draft.zonaHoraria;select.append(option);select.value=draft.zonaHoraria;}
    target.append(zone,dateField('fechaISO','Inicio de la celebración'),dateField('fechaFinISO','Fin de la celebración'),field('fechaTexto','Fecha que verán tus invitados','text','Se actualiza al cambiar la fecha. Puedes escribirla a tu gusto.'),field('horaTexto','Horario visible'));
  }
  const labels={marca:'Frase de la marca',temporada:'Nombre de la temporada',tema:'Referencia a Bridgerton',heroLinea1:'Titular principal',heroLinea2:'Titular en cursiva',heroEtiqueta:'Antetítulo de la portada',heroFrase:'Frase de la portada',heroBoton:'Botón de la portada',heroPie:'Texto lateral',heroFotoPie:'Pie de la foto principal',heroSello:'Texto del sello',navInvitacion:'Enlace a la invitación',navVelada:'Enlace a la velada',navDetalles:'Enlace a los detalles',navRsvp:'Botón de asistencia',gacetaMarca:'Nombre de la gaceta',gacetaEdicion:'Edición de la gaceta',gacetaSaludo:'Saludo al lector',gacetaTitulo:'Titular de la gaceta',gacetaFirma:'Firma de la cronista',cartaEtiqueta:'Numeración de la invitación',cartaTitulo:'Título de la invitación',cartaAbrir:'Botón para abrir la carta',cartaCerrar:'Botón para guardar la carta',cartaSello:'Frase sobre el sobre',cartaFirma:'Despedida de la carta',historiaEtiqueta:'Numeración de la historia',historiaTitulo:'Título de la historia',historiaCita:'Cita de la protagonista',relojEtiqueta:'Antetítulo del contador',relojTitulo:'Título del contador',relojFinal:'Mensaje al llegar la fecha',veladaEtiqueta:'Numeración de la velada',veladaTitulo:'Título del itinerario',veladaSubtitulo:'Descripción del itinerario',lugarEtiqueta:'Numeración del lugar',lugarTitulo:'Título del lugar',detallesEtiqueta:'Numeración de los detalles',vestimentaTitulo:'Título de vestimenta',vestimentaIntro:'Introducción de vestimenta',regalosTitulo:'Título de regalos',regalosSobres:'Texto de lluvia de sobres',copiarCuenta:'Botón de copiar cuenta',galeriaEtiqueta:'Antetítulo de la galería',galeriaTitulo:'Título de la galería',galeriaSubtitulo:'Descripción de la galería',rsvpEtiqueta:'Numeración del RSVP',whatsappBoton:'Botón para enviar por WhatsApp',whatsappNota:'Instrucción para enviar el mensaje',muroEtiqueta:'Antetítulo del libro de mensajes',muroTitulo:'Título del libro de mensajes',muroVacio:'Mensaje cuando el libro está vacío',despedida:'Frase de despedida',gracias:'Agradecimiento',footerTema:'Referencia a Bridgerton en el pie',saludo:'Saludo de invitación personalizada',puestos:'Texto de lugares reservados',placeholderNombre:'Ejemplo en el campo de nombre',placeholderCancion:'Ejemplo en el campo de canción',placeholderMensaje:'Ejemplo en el campo de mensaje'};
  Object.assign(labels,{heroSubtitulo:'Subtítulo de la portada',entradaEtiqueta:'Antetítulo de la entrada',entradaOmitir:'Botón para omitir la entrada',entradaPalacio:'Frase al entrar al palacio',entradaSobre:'Frase al recibir el sobre',entradaCarta:'Saludo escrito con pluma',entradaFirma:'Firma de Lady Whistledown',entradaRepetir:'Botón para repetir la entrada',retratoEtiqueta:'Pie del retrato',selloAceptado:'Texto del sello de aceptación',galeriaAnterior:'Botón de foto anterior',galeriaSiguiente:'Botón de siguiente foto',galeriaAyuda:'Instrucción de la galería'});
  function friendly(key){return labels[key] || key.replace(/([A-Z])/g,' $1').replace(/^./,letter=>letter.toUpperCase());}
  function renderTexts(){const target=$('#editorFields');target.append(field('fraseIntro','Mensaje de bienvenida','textarea'),field('carta','La carta de invitación','textarea','Separa los párrafos con un salto de línea.',{rows:8}),field('historia','La historia de la quinceañera','textarea','Escribe algo personal sobre ella.',{rows:5}),field('gaceta','La noticia de la gaceta','textarea'));const groups=[['La entrada al palacio',/^entrada/],['La portada y navegación',/^(marca|temporada|tema|nav|hero|cuando|donde|descubrir)/],['La gaceta',/^gaceta/],['La carta',/^carta/],['El retrato y la historia',/^(retrato|historia|nuevoCapitulo|primaveras)/],['El contador',/^(reloj|dias|horas|minutos|segundos|calendario)/],['El itinerario',/^velada/],['El lugar',/^(lugar|mapa|maps|waze)/],['Los detalles',/^(detalles|vestimenta|damas|caballeros|regalos|copiarCuenta)/],['La galería',/^galeria/],['El RSVP y los mensajes',/^(selloAceptado|rsvp|whatsapp|muro|saludo|puestos|corregir|masMensajes|placeholder)/],['La despedida y música',/^(footer|despedida|gracias|volverArriba|musica|sinMusica)/]];for(const[title,pattern]of groups){const detail=el('details','text-edit-group');detail.append(el('summary','edit-group-heading',title));Object.keys(draft.textos).filter(key=>pattern.test(key)).forEach(key=>detail.append(field('textos.'+key,friendly(key),/titulo|linea|cita|sello|nota|subtitulo/i.test(key)?'textarea':'text')));target.append(detail);}}
  function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('No se pudo leer el archivo.'));reader.readAsDataURL(file);});}
  async function imageData(file,isLogo=false){
    if(!/^image\/(jpeg|png|webp|gif|svg\+xml)$/.test(file.type))throw new Error('Selecciona una imagen JPG, PNG, WebP, GIF o SVG.');if(file.size>20*1024*1024)throw new Error('La imagen debe pesar menos de 20 MB.');
    const source=await readFile(file);if(/gif|svg/.test(file.type))return source;const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('La imagen no se pudo abrir.'));img.src=source;});
    const max=isLogo?600:1800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL(isLogo?'image/png':'image/webp',.88);
  }
  function imageEditor(path,title,{altPath,positionPath,isLogo=false,remove=false,index}={}){
    const card=el('div','image-editor');if(title)card.append(el('h3','',title));const preview=el('div','image-preview'),img=el('img');img.alt='Vista de la imagen seleccionada';const source=D.safeURL(get(path),true);if(source)img.src=source;else{img.hidden=true;preview.append(el('span','',isLogo?'Se usarán tus iniciales':'Sin imagen'));}img.onerror=()=>{img.hidden=true;preview.append(el('span','','Imagen no disponible'));};preview.append(img);card.append(preview);
    const actions=el('div','image-actions'),input=el('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/gif,image/svg+xml';input.hidden=true;input.id='upload-'+path.replace(/\./g,'-');
    const label=el('label','upload-label','↑ Subir imagen');label.htmlFor=input.id;input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;label.textContent='Preparando imagen…';try{set(path,await imageData(file,isLogo));img.src=get(path);img.hidden=false;preview.querySelectorAll('span').forEach(item=>item.remove());card.querySelector('[data-image-url]').value='';toast('Imagen añadida. Guarda los cambios cuando termines.');}catch(error){toast(error.message);}finally{label.textContent='↑ Subir imagen';input.value='';}});actions.append(label,input);
    const clear=el('button','small-button',isLogo?'Usar iniciales':remove?'Eliminar foto':'Restaurar imagen');clear.type='button';clear.addEventListener('click',()=>{if(isLogo)set(path,'');else if(remove){draft.fotos.splice(index,1);changed();}else set(path,path.split('.').reduce((value,key)=>value?.[key],window.EVENTO_BASE) || '');renderSection();});actions.append(clear);card.append(actions,el('p','file-caption','Los archivos subidos quedan incluidos en la descarga. Los enlaces externos requieren internet.'));
    const urlWrap=el('div','edit-field'),urlLabel=el('label','','O pega un enlace de imagen'),urlInput=el('input');urlInput.type='url';urlInput.id='url-'+path.replace(/\./g,'-');urlInput.dataset.imageUrl='true';urlLabel.htmlFor=urlInput.id;urlInput.placeholder=get(path)?.startsWith('data:')?'Imagen subida desde tu equipo':'https://…';urlInput.value=get(path)?.startsWith('data:')?'':get(path) || '';urlInput.addEventListener('change',()=>{const value=urlInput.value.trim();if(value&&!D.safeURL(value,true)){toast('Usa un enlace válido de imagen.');return;}set(path,value);if(value){img.hidden=false;img.src=value;preview.querySelectorAll('span').forEach(item=>item.remove());}else img.hidden=true;});urlWrap.append(urlLabel,urlInput);card.append(urlWrap);
    if(altPath)card.append(field(altPath,'Descripción de la imagen','text','Para las personas que usan un lector de pantalla.'));
    if(positionPath){const wrap=el('div','edit-field'),caption=el('label','','Encuadre de la imagen'),select=el('select');select.id='position-'+path.replace(/\./g,'-');caption.htmlFor=select.id;for(const[value,name]of [['50% 50%','Centro'],['50% 20%','Arriba · ideal para retratos'],['50% 80%','Abajo'],['25% 50%','Hacia la izquierda'],['75% 50%','Hacia la derecha']]){const option=el('option','',name);option.value=value;select.append(option);}if(![...select.options].some(option=>option.value===get(positionPath))){const option=el('option','','Encuadre actual');option.value=get(positionPath);select.append(option);}select.value=get(positionPath);img.style.objectPosition=get(positionPath);select.addEventListener('change',()=>{set(positionPath,select.value);img.style.objectPosition=select.value;});wrap.append(caption,select);card.append(wrap);}return card;
  }
  function orderButtons(arrayName,index){const wrap=el('div','repeat-row-controls');for(const[symbol,action,label]of [['↑',-1,'Subir'],['↓',1,'Bajar'],['×',0,'Eliminar']]){const btn=el('button','',symbol);btn.type='button';btn.setAttribute('aria-label',`${label} elemento ${index+1}`);btn.disabled=action<0&&index===0||action>0&&index===draft[arrayName].length-1;btn.addEventListener('click',()=>{if(action){const to=index+action;[draft[arrayName][index],draft[arrayName][to]]=[draft[arrayName][to],draft[arrayName][index]];}else draft[arrayName].splice(index,1);changed();renderSection();});wrap.append(btn);}return wrap;}
  function addButton(label,callback){const button=el('button','add-row',label);button.type='button';button.addEventListener('click',callback);$('#editorFields').append(button);}
  function renderImages(){
    const target=$('#editorFields');
    group('Carrusel automático de portada · 5 fotos');
    target.append(field('carruselPortada.segundos','Segundos entre cada foto','number','Las cinco imágenes se repiten automáticamente. Puedes elegir entre 3 y 15 segundos.',{min:3,max:15}));
    target.append(imageEditor('imagenes.portada','Foto 1 · La fotografía de portada',{altPath:'imagenes.portadaAlt',positionPath:'imagenes.portadaPosicion'}));
    draft.carruselPortada.fotos.forEach((photo,index)=>target.append(imageEditor(`carruselPortada.fotos.${index}.archivo`,`Foto ${index+2} · Carrusel de portada`,{altPath:`carruselPortada.fotos.${index}.alt`,positionPath:`carruselPortada.fotos.${index}.posicion`})));
    group('Las demás imágenes de tu invitación');
    target.append(imageEditor('retrato.archivo','El retrato de la quinceañera',{altPath:'retrato.alt',positionPath:'retrato.posicion'}));
    for(const[key,title]of [['historia','La foto de tu historia'],['lugar','La fotografía del lugar'],['vestimenta','El detalle de vestimenta']])target.append(imageEditor('imagenes.'+key,title,{altPath:'imagenes.'+key+'Alt',positionPath:'imagenes.'+key+'Posicion'}));
    target.append(imageEditor('imagenes.monograma','Tu monograma',{isLogo:true}));
    group('El álbum de la temporada');
    draft.fotos.forEach((photo,index)=>{const wrap=el('div','repeat-row'),head=el('div','repeat-row-head');head.append(el('b','',`Foto ${index+1}`),orderButtons('fotos',index));wrap.append(head,imageEditor(`fotos.${index}.archivo`,'',{altPath:`fotos.${index}.alt`,positionPath:`fotos.${index}.posicion`,remove:true,index}),field(`fotos.${index}.texto`,'Pie de fotografía'));target.append(wrap);});
    addButton('+ Añadir fotografía',()=>{draft.fotos.push({archivo:'',texto:'',alt:'',posicion:'50% 50%'});changed();renderSection();$('.editor-controls').scrollTop=$('.editor-controls').scrollHeight;});
  }
  function renderTimeline(){draft.itinerario.forEach((moment,index)=>{const card=el('div','repeat-row'),head=el('div','repeat-row-head');head.append(el('b','',String(index+1).padStart(2,'0')),orderButtons('itinerario',index));card.append(head,field(`itinerario.${index}.hora`,'Hora'),field(`itinerario.${index}.titulo`,'Momento'),field(`itinerario.${index}.detalle`,'Descripción (opcional)'));$('#editorFields').append(card);});addButton('+ Añadir momento',()=>{draft.itinerario.push({hora:'',titulo:'',detalle:''});changed();renderSection();$('.editor-controls').scrollTop=$('.editor-controls').scrollHeight;});}
  function renderVenue(){$('#editorFields').append(field('lugar.nombre','Nombre del lugar'),field('lugar.salon','Salón o espacio'),field('lugar.direccion','Dirección','textarea'),field('lugar.googleMaps','Enlace de Google Maps','url'),field('lugar.waze','Enlace de Waze','url'),field('lugar.mapaConsulta','Lugar que se mostrará en el mapa','text','Escribe el nombre del establecimiento o su dirección.'),field('lugar.notaImagen','Pie de la imagen del lugar','text','Si subes una fotografía real, cambia la nota de ambientación.'));}
  function renderDetails(){const target=$('#editorFields');group('Código de vestimenta');target.append(field('vestimenta.titulo','Código de vestimenta'),field('vestimenta.damas','Vestimenta para damas'),field('vestimenta.caballeros','Vestimenta para caballeros'),field('vestimenta.nota','Nota adicional (opcional)','textarea'));group('Los regalos');target.append(field('regalos.mensaje','Mensaje sobre regalos','textarea'),field('regalos.lluviaDeSobres','Mostrar lluvia de sobres','checkbox'));group('Datos bancarios (opcionales)');target.append(field('regalos.banco','Banco'),field('regalos.cuenta','Número de cuenta','text','Si está vacío, los datos bancarios no se muestran.'),field('regalos.titular','Titular de la cuenta'));group('Tiendas y listas de regalos');draft.regalos.tiendas.forEach((store,index)=>{const card=el('div','repeat-row');card.append(field(`regalos.tiendas.${index}.nombre`,'Nombre de la tienda'),field(`regalos.tiendas.${index}.url`,'Enlace a la lista','url'));const remove=el('button','small-button danger','Eliminar tienda');remove.type='button';remove.addEventListener('click',()=>{draft.regalos.tiendas.splice(index,1);changed();renderSection();});card.append(remove);target.append(card);});addButton('+ Añadir tienda',()=>{draft.regalos.tiendas.push({nombre:'',url:''});changed();renderSection();});}
  function renderRsvp(){const target=$('#editorFields');notice('Usa el código del país seguido del número. Ejemplo de formato en Panamá: +507 6000 0000.');target.append(field('rsvp.whatsapp','WhatsApp que recibirá las confirmaciones','tel','Puedes escribirlo con +, espacios o guiones. Se normaliza automáticamente.'),field('rsvp.fechaLimite','Fecha límite para responder'),field('rsvp.titulo','Título del RSVP','textarea'),field('rsvp.subtitulo','Mensaje del RSVP','textarea'),field('rsvp.mensajeGracias','Agradecimiento al guardar la respuesta','textarea'));group('Los campos y botones');for(const[key,label]of [['etiquetaNombre','Etiqueta del nombre'],['etiquetaAsistencia','Pregunta de asistencia'],['opcionSi','Opción para asistir'],['opcionNo','Opción para no asistir'],['etiquetaCancion','Etiqueta de la canción'],['etiquetaMensaje','Etiqueta del mensaje'],['boton','Botón del formulario'],['errorNombre','Aviso cuando falta el nombre'],['errorAsiste','Aviso cuando falta la asistencia']])target.append(field('rsvp.'+key,label));group('Invitaciones personalizadas');notice('En tu enlace publicado puedes añadir ?para=Familia%20García&p=3 para saludar a esa familia y reservar 3 lugares. Con la base de datos también se conserva ?f=codigo-de-familia.');}
  function renderMusic(){const target=$('#editorFields');target.append(field('musica.titulo','Nombre de la música'),field('musica.volumen','Volumen inicial','range','De 0 (silencio) a 1 (máximo).',{min:0,max:1,step:.05}));const wrap=el('div','image-editor');wrap.append(el('h3','','Tu archivo de audio'));const input=el('input');input.type='file';input.id='uploadAudio';input.accept='audio/*,.mp3,.m4a,.ogg,.wav';input.hidden=true;const label=el('label','upload-label','↑ Subir audio');label.htmlFor=input.id;const current=el('p','file-caption',draft.musica.archivo?'Audio configurado. Se incluirá en la descarga.':'Todavía no has subido un archivo.');input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;if(file.size>25*1024*1024){toast('Usa un audio de menos de 25 MB.');return;}if(!file.type.startsWith('audio/')&&!/\.(mp3|m4a|ogg|wav)$/i.test(file.name)){toast('Selecciona un archivo de audio.');return;}try{let audio=await readFile(file);if(!file.type)audio=audio.replace(/^data:;base64,/,'data:audio/mpeg;base64,');set('musica.archivo',audio);current.textContent=file.name+' · Incluido en la invitación.';toast('Audio añadido.');}catch(error){toast(error.message);}});const reset=el('button','small-button','Quitar audio');reset.type='button';reset.addEventListener('click',()=>{set('musica.archivo','');renderSection();});const actions=el('div','image-actions');actions.append(label,input,reset);wrap.append(actions,current);target.append(wrap,field('musica.archivo','O un enlace directo al audio','url','El archivo de audio tiene prioridad sobre YouTube.'));if(draft.musica.archivo.startsWith('data:')){$('#edit-musica-archivo').value='';$('#edit-musica-archivo').placeholder='Audio subido desde tu equipo';}group('YouTube (alternativa)');target.append(field('musica.youtube','ID del video de YouTube','text','Los 11 caracteres que van después de v= en el enlace. Requiere internet.'));const off=el('button','small-button','Desactivar toda la música');off.type='button';off.addEventListener('click',()=>{draft.musica.archivo='';draft.musica.youtube='';changed();renderSection();});target.append(off);}
  function renderAdvanced(){const target=$('#editorFields');group('La experiencia Bridgerton');target.append(field('experiencia.entrada','Mostrar la entrada al palacio','checkbox','Palacio, sobre y carta en una secuencia de unos 10 segundos con Omitir.'),field('experiencia.jardin','Mostrar el jardín animado','checkbox'),field('experiencia.cursor','Usar el cursor temático','checkbox','Se aplica en computadoras con ratón.'));const replay=el('button','small-button','Ver la entrada en la vista previa');replay.type='button';replay.addEventListener('click',()=>$('#previewFrame').contentWindow.postMessage({type:'invitation:entry'},location.protocol==='file:'?'*':location.origin));target.append(replay);group('Guardar y compartir');notice('Guardar cambios actualiza este navegador. Descargar invitación crea un HTML independiente con tus datos, fotos y tipografías. Puedes publicarlo como index.html en tu alojamiento web.');const actions=el('div','image-actions');for(const[text,fn]of [['↓ Guardar respaldo',backup],['↑ Importar respaldo',()=>$('#importFile').click()]]){const button=el('button','small-button',text);button.type='button';button.addEventListener('click',fn);actions.append(button);}target.append(actions);group('Base de datos de invitados (opcional)');notice('WhatsApp funciona sin servidor. Si ya tienes Supabase y sus reglas de acceso configuradas, puedes guardar confirmaciones y mostrar mensajes públicos aprobados. Usa únicamente una clave pública anon, nunca una service_role.');target.append(field('supabase.habilitado','Guardar respuestas en Supabase','checkbox'),field('supabase.url','URL del proyecto Supabase','url'),field('supabase.clave','Clave pública anon','textarea','La clave pública se incluye en la invitación. Las reglas de tu proyecto protegen los datos.'));group('Volver al diseño inicial');const reset=el('button','small-button danger','Restaurar el diseño inicial');reset.type='button';reset.addEventListener('click',()=>{backup();draft=D.clone(window.EVENTO_BASE);changed();renderSection();sendPreview();toast('Se descargó un respaldo y se restauró el diseño inicial.');});target.append(reset);}
  const renderers={celebracion:renderCelebration,textos:renderTexts,imagenes:renderImages,itinerario:renderTimeline,lugar:renderVenue,detalles:renderDetails,rsvp:renderRsvp,musica:renderMusic,avanzado:renderAdvanced};
  function renderSection(){const section=sections.find(s=>s[0]===active);$('#editorNumber').textContent=String(sections.indexOf(section)+1).padStart(2,'0');$('#editorEyebrow').textContent=section[3];$('#editorTitle').textContent=section[2];$('#editorNote').textContent=section[4];$('#editorFields').replaceChildren();renderers[active]();$('#editorNav').querySelectorAll('button').forEach(btn=>btn.setAttribute('aria-current',btn.dataset.section===active?'page':'false'));}
  for(const[index,section]of sections.entries()){const button=el('button');button.type='button';button.dataset.section=section[0];button.append(el('span','',String(index+1).padStart(2,'0')),el('span','',section[1]));button.addEventListener('click',()=>{active=section[0];renderSection();$('.editor-controls').scrollTop=0;$('#previewFrame').contentWindow.postMessage({type:'invitation:section',section:section[5]},location.protocol==='file:'?'*':location.origin);});$('#editorNav').append(button);}
  async function save(){const errors=D.validate(draft);if(errors.length){showErrors(errors);return false;}try{await D.save(draft);dirty=false;$('#saveStatus').textContent='Todos los cambios guardados';toast('Cambios guardados en este navegador.');return true;}catch{showErrors(['No se pudo guardar en este navegador. Descarga un respaldo o la invitación para conservar tus cambios.']);return false;}}
  function filename(prefix,ext){const name=draft.nombreCompleto.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return prefix+'-'+(name || 'mis-xv')+'.'+ext;}
  async function exportInvitation(){const errors=D.validate(draft);if(!draft.supabase.habilitado&&!/^[1-9]\d{7,14}$/.test(draft.rsvp.whatsapp.replace(/[\s()+-]/g,'')))errors.push('Añade el WhatsApp que recibirá las respuestas antes de descargar la invitación.');if(errors.length){showErrors(errors);return;}const buttons=[$('#exportButton'),$('#mobileExport')];buttons.forEach(b=>b.disabled=true);try{const html=InvitationExport.createHTML(draft);InvitationExport.download(html,filename('invitacion','html'));try{await D.save(draft);dirty=false;$('#saveStatus').textContent='Todos los cambios guardados';}catch{/* the downloaded file already preserves the config */}toast('Invitación descargada con tu información y tus imágenes.');}catch(error){showErrors([error.message]);}finally{buttons.forEach(b=>b.disabled=false);}}
  function backup(){InvitationExport.download(JSON.stringify(draft,null,2),filename('respaldo','json'),'application/json;charset=utf-8');toast('Respaldo descargado. Puedes importarlo después para seguir editando.');}
  async function importBackup(event){const file=event.target.files[0];if(!file)return;if(file.size>75*1024*1024){toast('El respaldo debe pesar menos de 75 MB.');return;}try{const imported=JSON.parse(await file.text());if(!imported||typeof imported!=='object'||!imported.nombreCompleto||imported.version!==1)throw new Error('Selecciona un respaldo de esta invitación.');const next=D.merge(window.EVENTO_BASE,imported),errors=D.validate(next);if(errors.length)throw new Error(errors.join('\n'));draft=next;changed();renderSection();sendPreview();toast('Respaldo importado. Revisa la vista previa y guarda los cambios.');}catch(error){showErrors([error.message || 'No se pudo importar el respaldo.']);}finally{event.target.value='';}}
  $('#saveButton').addEventListener('click',save);$('#mobileSave').addEventListener('click',save);$('#exportButton').addEventListener('click',exportInvitation);$('#mobileExport').addEventListener('click',exportInvitation);$('#backupButton').addEventListener('click',backup);$('#importFile').addEventListener('change',importBackup);$('#editorForm').addEventListener('submit',event=>event.preventDefault());
  $('#desktopPreview').addEventListener('click',()=>{$('#previewStage').classList.remove('mobile');$('#desktopPreview').setAttribute('aria-pressed','true');$('#mobilePreview').setAttribute('aria-pressed','false');});$('#mobilePreview').addEventListener('click',()=>{$('#previewStage').classList.add('mobile');$('#desktopPreview').setAttribute('aria-pressed','false');$('#mobilePreview').setAttribute('aria-pressed','true');});$('#showPreview').addEventListener('click',()=>{const open=$('#previewStage').classList.toggle('open');$('#showPreview').textContent=open?'Ocultar vista previa':'Ver vista previa';});
  $('#previewFrame').addEventListener('load',()=>{previewReady=true;sendPreview();});window.addEventListener('message',event=>{if(event.source!==$('#previewFrame').contentWindow||(location.protocol!=='file:'&&event.origin!==location.origin))return;if(event.data?.type==='invitation:ready'){previewReady=true;sendPreview();}});
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
  renderSection();updatePhone();previewReady=true;sendPreview();
})();
